wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.17.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686203165.17178
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 33
      - 49
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.8.16
      5: 0.15.4
      6: 4.17.0.dev0
      8:
      - 5
data_dir:
  desc: null
  value: ''
schedule_sampler:
  desc: null
  value: uniform
lr:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.0
lr_anneal_steps:
  desc: null
  value: 400000
batch_size:
  desc: null
  value: 64
microbatch:
  desc: null
  value: -1
ema_rate:
  desc: null
  value: '0.9999'
log_interval:
  desc: null
  value: 50
save_interval:
  desc: null
  value: 50000
resume_checkpoint:
  desc: null
  value: ''
use_fp16:
  desc: null
  value: false
fp16_scale_growth:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 101
gradient_clipping:
  desc: null
  value: -1.0
eval_interval:
  desc: null
  value: 2000
checkpoint_path:
  desc: null
  value: diffusion_models/diff_bert_pad_rand128_transformer_lr0.0001_0.0_2000_sqrt_Lsimple_h128_s2_d0.1_sd101_xstart_e2e
image_size:
  desc: null
  value: 8
num_channels:
  desc: null
  value: 128
num_res_blocks:
  desc: null
  value: 2
num_heads:
  desc: null
  value: 4
num_heads_upsample:
  desc: null
  value: -1
attention_resolutions:
  desc: null
  value: 16,8
dropout:
  desc: null
  value: 0.1
learn_sigma:
  desc: null
  value: false
sigma_small:
  desc: null
  value: false
class_cond:
  desc: null
  value: false
diffusion_steps:
  desc: null
  value: 2000
noise_schedule:
  desc: null
  value: sqrt
timestep_respacing:
  desc: null
  value: ''
use_kl:
  desc: null
  value: false
predict_xstart:
  desc: null
  value: true
rescale_timesteps:
  desc: null
  value: true
rescale_learned_sigmas:
  desc: null
  value: true
use_checkpoint:
  desc: null
  value: false
use_scale_shift_norm:
  desc: null
  value: true
model_arch:
  desc: null
  value: transformer
in_channel:
  desc: null
  value: 128
out_channel:
  desc: null
  value: 128
training_mode:
  desc: null
  value: bert
vocab_size:
  desc: null
  value: 11043
config_name:
  desc: null
  value: bert-base-uncased
experiment_mode:
  desc: null
  value: lm
logits_mode:
  desc: null
  value: 1
modality:
  desc: null
  value: bert
dataset_name:
  desc: null
  value: wikitext
dataset_config_name:
  desc: null
  value: wikitext-2-raw-v1
config:
  desc: null
  value: diffusion_lm/synthetic_data/configs/emnlp2020/experiments/difflm_seed0_m3_k128_trainc20000.yaml
model_name_or_path:
  desc: null
  value: predictability/diff_models/compress_e=5_b=60_m=gpt2_wikitext-103-raw-v1_None
experiment:
  desc: null
  value: random
roc_train:
  desc: null
  value: ../datasets/ROCstory
wiki_train:
  desc: null
  value: diffusion_lm/simple_wiki/data.v1.split/simple.training.txt
e2e_train:
  desc: null
  value: e2e_data
yelp_train:
  desc: null
  value: diffusion_lm/yelpnlg-resources/yelpnlg-corpus
commonGen_train:
  desc: null
  value: diffusion_lm/common-gen/commongen_data
emb_scale_factor:
  desc: null
  value: 1.0
noise_level:
  desc: null
  value: 0.0
cache_mode:
  desc: null
  value: 'no'
use_bert_tokenizer:
  desc: null
  value: 'no'
padding_mode:
  desc: null
  value: pad
preprocessing_num_workers:
  desc: null
  value: 1
